### ISSUE TITLE
확률을 임의로 정할 수 있는 함수 구현을 해주셨으면 좋겠습니다.

### ISSUE THREAD

**Issue by DevJeyeong** [andrewjeongtheawesome/rsp#6]
예시를 들자면, 내가 이길 확률 80%, 컴퓨터가 이길 확률 20%와 같이 사용자가 직접 정할 수 있도록 메인 함수를 구현해주셨으면 좋을 것 같습니다.

**Comment by junhg0211** [comment]
#13 PR을 통해서 resolved
